Implement double click
lignumqt/ESTC-project pull request #13
Opened 2021-11-17 17:42 UTC by lignumqt

2021-11-19 13:00 UTC, Diadlo requested changes

2021-11-19 13:00 UTC, Diadlo commented on modules/gpio/button.h
>  void board_buttons_init(void);
Лучше дать всем функциям в модуле единый префикс

2021-11-23 09:29 UTC, lignumqt commented on modules/gpio/button.h
> +extern bool was_double_click;
вы имеете ввиду написать функцию в модуле button, которая будет возвращать значение was_double_click?

2021-11-23 16:38 UTC, lignumqt commented on modules/gpio/button.h
> +extern bool was_double_click;
сделал как написал

2021-11-24 06:24 UTC, Diadlo commented on modules/gpio/button.h
> +extern bool was_double_click;
Да, именно это я и имел в виду)

2021-11-24 06:25 UTC, Diadlo approved these changes

2021-11-24 06:27 UTC, merged