Use GPIO to control LED #3
lignumqt/ESTC-project pull request #4
Opened 2021-11-05 12:50 UTC by lignumqt

close issues #3

2021-11-06 12:33 UTC, Diadlo requested changes

2021-11-06 12:33 UTC, Diadlo commented on modules/gpio/gpio.c
> +void __gpio_output_voltage_setup(void)
Can you clarify, why do we need this function? Also, why does it has `__` prefix?

2021-11-06 12:33 UTC, Diadlo commented on modules/gpio/gpio.c
> +#if defined(BOARD_PCA10059)
Do you have plans to support other boards?

2021-11-06 12:33 UTC, Diadlo commented on modules/gpio/gpio.c
> +    (void) nrf_dfu_trigger_usb_init();
Why do you call this function?

2021-11-06 12:34 UTC, Diadlo commented on modules/gpio/gpio.c
> +    #if defined(BOARDS_WITH_USB_DFU_TRIGGER) && defined(BOARD_PCA10059)
What is DFU_TRIGGER? Why do you need to support it?

2021-11-07 09:56 UTC, lignumqt commented on modules/gpio/gpio.c
> +void __gpio_output_voltage_setup(void)
ну если я правильно понял из комментария, то это нужно для повышения напряжения до 3В, что бы синий и зеленый светодиоды смогли загореться
префикс для того что бы не было конфликта имен с исходниками SDK, и что бы как то отличать визуально свои функции

2021-11-07 09:58 UTC, lignumqt commented on modules/gpio/gpio.c
> +    (void) nrf_dfu_trigger_usb_init();
взял из исходников, не уверен нужна ли она, но есть препроцессорные условия которые ограничивают когда она требуется

2021-11-07 09:58 UTC, lignumqt commented on modules/gpio/gpio.c
> +    #if defined(BOARDS_WITH_USB_DFU_TRIGGER) && defined(BOARD_PCA10059)
ответил  предыдущем комментарии

2021-11-07 10:16 UTC, Diadlo commented on modules/gpio/gpio.c
> +void __gpio_output_voltage_setup(void)
А что в них "своего"?

2021-11-07 10:17 UTC, Diadlo commented on modules/gpio/gpio.c
> +    (void) nrf_dfu_trigger_usb_init();
А почему вы просто скопировали из исходников, а не разобрались и не написали сами?

2021-11-07 19:29 UTC, Diadlo approved these changes

2021-11-08 06:34 UTC, merged