Use GPIO to work with button #5
lignumqt/ESTC-project pull request #6
Opened 2021-11-05 14:19 UTC by lignumqt

2021-11-06 12:44 UTC, Diadlo requested changes

2021-11-06 12:44 UTC, Diadlo commented on modules/gpio/led.h
> +#define led_seq {LED_IDX_1, LED_IDX_1, LED_IDX_0, LED_IDX_0, LED_IDX_0, LED_IDX_3}
Why did you select this sequence?

2021-11-06 12:44 UTC, Diadlo commented on modules/gpio/gpio.c
> +uint32_t __nrf_gpio_pin_read(uint32_t pin_number)
Why does this function start with `__`?

2021-11-07 09:07 UTC, lignumqt commented on modules/gpio/led.h
> +#define led_seq {LED_IDX_1, LED_IDX_1, LED_IDX_0, LED_IDX_0, LED_IDX_0, LED_IDX_3}
было взято из задания:
Example for the sequence: RRGGGB
возможно не совсем очевидно какой индекс за какой цвет отвечает
поправил это

2021-11-07 11:34 UTC, Diadlo commented on modules/gpio/led.h
> +#define led_seq {LED_IDX_1, LED_IDX_1, LED_IDX_0, LED_IDX_0, LED_IDX_0, LED_IDX_3}
Это был пример для демпонстрации логики задания. Последовательность у вас должна остаться той же, что была раньше

2021-11-07 11:35 UTC, Diadlo commented on modules/gpio/gpio.c
> +uint32_t __nrf_gpio_pin_read(uint32_t pin_number)
Если вы делаете "свои" функции, то не надо им добавлять префикс `nrf_`

2021-11-07 16:19 UTC, closed without merging